
name: api-ci

on:
  push:
    branches: [master]
    paths:
      - "api/**"
  pull_request:
    branches: [master]
    paths:
      - "api/**"    
jobs: 
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build api
        run: docker-compose up -d api
      - name: Run test
        run: docker-compose run api python manage.py test
  coverage:
    needs: [ build_and_test ]
    runs-on: ubuntu-latest
    name: coverage
    steps:
    - uses: actions/checkout@master
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: 806251845d79d7472d90d5efaae94b54a4ee5adc159386813d99563eb86c2468
      with:
        coverageLocations: ${{github.workspace}}/api/*
  sonarcloud-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.4
        with:
          projectBaseDir: api
        env:
          SONAR_TOKEN: 0f46fa26c986db48840be910cb8cb85bcaddf199
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
