
name: api-ci

on:
  push:
    branches: [master]
    paths:
      - "api/**"
  pull_request:
    branches: [master]
    paths:
      - "api/**"    
jobs: 
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build api
        run: docker-compose up -d api
      - name: Run test
        run: docker-compose run api python manage.py test
  coverage:
    needs: [ build_and_test ]
    runs-on: ubuntu-latest
    name: coverage
    steps:
    - uses: actions/checkout@master
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: 806251845d79d7472d90d5efaae94b54a4ee5adc159386813d99563eb86c2468
      with:
        coverageLocations: ${{github.workspace}}/api/*
  sonarcloud-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.4
        with:
          projectBaseDir: api
        env:
          SONAR_TOKEN: be937845fd108c66d46c654c77faf77b0372dbc7
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  heroku_git_deploy_job:
      needs: [ build_and_test,sonarcloud-analysis ]
      runs-on: ubuntu-latest
      name: Git Deploy job- A job to deploy django app to heroku using git
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy django to heroku
          uses: akhileshns/heroku-deploy@v3.4.6
          with: 
            heroku_api_key: d8dfe858-2bcf-4039-817b-e3b517519573
            heroku_app_name : gces-api2
            heroku_email: 'lucasleitemm@hotmail.com'
            appdir: api
