
name: api-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build api
        run: docker-compose up -d api
      - name: Run test
        run: |
          docker-compose run api python manage.py test
  coverage:
    runs-on: ubuntu-latest
    name: coverage
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: npm build
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: 806251845d79d7472d90d5efaae94b54a4ee5adc159386813d99563eb86c2468
      with:
        coverageCommand: npm run coverage
        coverageLocations: ${{github.workspace}}/api/*
