# This is a basic workflow to help you get started with Actions

name: client ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
     - "client/**"
  pull_request:
    branches: [ master ]
    paths:
     - "client/**"
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build client
        run: docker-compose up -d client
      - name: Run tests
        run: docker-compose run client quasar test --unit jest
